CV_LIBS := -lopencv_objdetect -lopencv_shape -lopencv_videostab -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_video -lopencv_photo -lopencv_photo -lopencv_ml -lopencv_imgproc -lopencv_flann -lopencv_core -lopencv_hal

all:
	g++ main.cpp -L/usr/local/lib -o "pi_v1" $(CV_LIBS)
